[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imvi"
version = "0.1.0"
requires-python = ">= 3.8"
authors = [{name = "Joerg Neulist", email = "21063011+joergneulist@users.noreply.github.com"}]
license = "MIT"
readme = "README.md"

[project.scripts]
imvi = "imvi:main"
