#!/bin/sh

case "$1" in
  start)
    echo "Starting Image Viewer"
    # Use start-stop-daemon to run in the background (&) 
    # and save the process ID (pid) to a file.
    start-stop-daemon -S -b -m -p /var/run/myapp.pid -x /usr/bin/imvi
    ;;
  stop)
    echo "Stopping My Python App..."
    start-stop-daemon -K -p /var/run/myapp.pid
    rm -f /var/run/myapp.pid
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
